### ISSUE TITLE
safe_os fact fails with ruby 2.7

### ISSUE THREAD

**Issue by led0ch** [GeoffWilliams/puppet-safe_roles#6]
hey @GeoffWilliams 

it seems that safe_os (from the latest module v1.2.2)  fails on systems with ruby 2.7.3  (which comes with puppet-enterprise-2021.2.0 and facter v 4.2.1).
I get:
`Error: Facter: Error while resolving custom fact fact='safe_os', resolution='<anonymous>': can't modify frozen String: "RedHat"`
while on older setups it works without any issues  (tested on ruby 2.5.8p224 with facter  3.14.10).

seems that Ruby 2.7  introduced this: 
https://rubyreferences.github.io/rubychanges/2.7.html#core-methods-returning-frozen-strings

led0ch

**Comment by GeoffWilliams** [comment]
Thanks for the report, made fixing this much simpler. Fix is released, please test

**Comment by led0ch** [comment]
Thanks @GeoffWilliams  - that was quick!

Tested and confirmed to work OK:

`# facter -p safe_os
{
  architecture => "x86_64",
  distro => {
    codename => "ootpa",
    description => "red_hat_enterprise_linux_release_8.4_(ootpa)",
    id => "redhatenterprise",
    release => {
      full => "8.4",
      major => "8",
      minor => "4"
    },
    specification => ":core-4.1-amd64:core-4.1-noarch"
  },
`

Thanks!
led0ch
