### ISSUE TITLE
Safe role does not resolve if the role is 10 characters on Ubuntu 20.04

### ISSUE THREAD

**Issue by benjamin-robertson** [GeoffWilliams/puppet-safe_roles#9]
This possibly affects more OS's and different role lengths.

### Setup

- PE 2019.8.11
- Ubuntu 20.04
- Puppet Agent 6.27.0
- OpenSSL 1.1.1f  31 Mar 2020
- 10 character pp_role, 'role::spam'

### Issue

safe_pp_role resolves to '.'
<img width="386" alt="image" src="https://user-images.githubusercontent.com/72488257/182314877-92eb74f0-44d5-4566-808d-46429e0dc303.png">

Even when the pp_role is
<img width="854" alt="image" src="https://user-images.githubusercontent.com/72488257/182314985-3e745be3-b194-4eb0-88ee-17da18779d03.png">

When pp_role is 12 characters; role works
<img width="429" alt="image" src="https://user-images.githubusercontent.com/72488257/182315114-cd73f6d5-8544-41ee-a59f-83eb6bdac698.png">

### Cause

As safe roles relies on OpenSSL text output to stout to interrogate certificates; any issue with the output will cause safe_roles to stop working.

In this case; OpenSSL has inserted an extra carriage return after '1.3.6.1.4.1.34380.1.1.13:'
<img width="614" alt="image" src="https://user-images.githubusercontent.com/72488257/182315447-55d86843-55ad-414f-9cc6-ab315bec0aa6.png">

This is an issue with OpenSSL as this issue does not occur within the Windows Certificate viewer or in the OSX viewer
<img width="237" alt="image" src="https://user-images.githubusercontent.com/72488257/182316154-904b10b8-1b50-4570-a71c-e9b7e25a3590.png">

### Solution

Getting this corrected in OpenSSL will probably not be that straight forward. Consider using rubys build in library to lookup certificate details. 

Fixed in #11

**Comment by GeoffWilliams** [comment]
I concur that changing openssl will not be simple ;-) If you want to take over maintenance of this module I'm happy for you to do so and implement the chance you suggested.

**Comment by benjamin-robertson** [comment]
Happy to fix this issue; PR raised against master for you.

**Comment by GeoffWilliams** [comment]
fix released in v1.3.0 and published to puppet forge

**Comment by benjamin-robertson** [comment]
Awesome; thanks for you quick merge and publish 👍
